# Azure Pipelines entry point
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

stages:
- stage: UnitTest
  displayName: Unit Tests
  jobs:
  - template: pipelines/templates/unit_test.yml
    parameters:
      vmImage: 'ubuntu-22.04'                 # ローカルと同じにする
      buildDir: 'build'
      buildType: 'Debug'
      # TI SDK（必要なら）
      sdkRoot: '$(Agent.ToolsDirectory)/ti-processor-sdk-am62xx'
      # カバレッジ出力先
      coverageDir: 'coverage'
